# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: apartments_test
          POSTGRES_USER: sj
          POSTGRES_PASSWORD: mypassword
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://sj:password@localhost:5432/apartments_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
          
      - name: Build Docker image
        run: docker-compose build

      - name: Start Docker containers
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 15

      - name: Set up database schema
        run: docker-compose exec app bin/rails db:schema:load

      - name: Run tests
        run: docker-compose exec app bin/rake

      - name: Stop Docker containers
        run: docker-compose down
